# note another comments
- src: github.com/kr/pat
  branch: master

- src: github.com/araddon/gou#ec9b02c2

- src: github.com/araddon/elastigo
  branch: newsearch
  as: github.com/mattbaird/elastigo 

# note we can have comments
#- src: Path
#  hash: Hash
#  branch: Branch


